import { readdir, readFile, writeFile, mkdir, rm } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const docsDir = path.join(root, "docs");
const outDir = path.join(root, "src", "generated");
const outFile = path.join(outDir, "guide-data.ts");
const bodiesDir = path.join(outDir, "bodies");

// Parse a front-matter list value such as `[null-safety, "smart cast"]` into a
// normalized, lowercased string array. Accepts quoted or unquoted items.
function parseTags(raw) {
  if (!raw) {
    return [];
  }
  const inner = raw.trim().replace(/^\[/, "").replace(/\]$/, "");
  return inner
    .split(",")
    .map((tag) => tag.trim().replace(/^["']|["']$/g, "").trim().toLowerCase())
    .filter(Boolean);
}

function parseFrontMatter(raw, file) {
  if (!raw.startsWith("---\n")) {
    throw new Error(`${file}: missing front matter`);
  }
  const end = raw.indexOf("\n---\n", 4);
  if (end === -1) {
    throw new Error(`${file}: unterminated front matter`);
  }

  const front = raw.slice(4, end).trim();
  const body = raw.slice(end + "\n---\n".length).trim();
  const meta = {};

  for (const line of front.split("\n")) {
    const match = line.match(/^([a-zA-Z0-9_-]+):\s*(.*)$/);
    if (!match) {
      throw new Error(`${file}: invalid front matter line: ${line}`);
    }
    const [, key, value] = match;
    meta[key] = value.replace(/^"(.*)"$/, "$1");
  }

  const required = ["title", "category", "language", "order", "summary"];
  for (const key of required) {
    if (!meta[key]) {
      throw new Error(`${file}: missing ${key}`);
    }
  }
  meta.order = Number(meta.order);
  if (!Number.isFinite(meta.order)) {
    throw new Error(`${file}: order must be numeric`);
  }
  meta.tags = parseTags(meta.tags);

  return { meta, body };
}

const files = (await readdir(docsDir)).filter((file) => file.endsWith(".md")).sort();

const docs = [];
for (const file of files) {
  const raw = await readFile(path.join(docsDir, file), "utf8");
  const { meta, body } = parseFrontMatter(raw, file);
  docs.push({
    id: file.replace(/^\d+-/, "").replace(/\.md$/, ""),
    file,
    title: meta.title,
    category: meta.category,
    language: meta.language,
    order: meta.order,
    summary: meta.summary,
    tags: meta.tags,
    body,
    wordCount: body.split(/\s+/).filter(Boolean).length,
  });
}

docs.sort((a, b) => a.order - b.order || a.title.localeCompare(b.title));

await mkdir(outDir, { recursive: true });

// Each document body is emitted as its own module so Vite can code-split it into
// a lazy chunk (loaded via loadDocBody() only when that page is opened). Rebuild
// the directory from scratch each run so renamed/removed docs leave no orphans.
await rm(bodiesDir, { recursive: true, force: true });
await mkdir(bodiesDir, { recursive: true });
for (const doc of docs) {
  await writeFile(
    path.join(bodiesDir, `${doc.id}.ts`),
    `// AUTO-GENERATED body for ${doc.file}. Do not edit by hand.\nexport default ${JSON.stringify(doc.body)};\n`,
    "utf8",
  );
}

// Only metadata (small: titles, summaries, tags) is bundled eagerly.
const meta = docs.map((doc) => ({
  id: doc.id,
  file: doc.file,
  title: doc.title,
  category: doc.category,
  language: doc.language,
  order: doc.order,
  summary: doc.summary,
  tags: doc.tags,
  wordCount: doc.wordCount,
}));

const loaderLines = docs
  .map((doc) => `  ${JSON.stringify(doc.id)}: () => import("./bodies/${doc.id}"),`)
  .join("\n");

const output = `// AUTO-GENERATED by scripts/build-data.mjs. Do not edit by hand.
// Run \`bun scripts/build-data.mjs\` (or \`bun run dev\`) to regenerate.
//
// Document metadata is bundled eagerly (titles, summaries, tags — small).
// Each document body lives in ./bodies/<id>.ts and is loaded on demand via
// loadDocBody(), so Vite emits one lazy chunk per document instead of shipping
// every page's markdown in the initial download.

export interface GuideDoc {
  id: string;
  file: string;
  title: string;
  category: string;
  language: string;
  order: number;
  summary: string;
  tags: string[];
  wordCount: number;
}

export const guideDocs: GuideDoc[] = ${JSON.stringify(meta, null, 2)};

const bodyLoaders: Record<string, () => Promise<{ default: string }>> = {
${loaderLines}
};

/** Lazily load a document's rendered markdown body. Resolves to "" for unknown ids. */
export function loadDocBody(id: string): Promise<string> {
  const loader = bodyLoaders[id];
  return loader ? loader().then((mod) => mod.default) : Promise.resolve("");
}
`;

await writeFile(outFile, output, "utf8");

const tagSet = new Set(docs.flatMap((doc) => doc.tags));
console.log(
  `Generated ${path.relative(root, outFile)} + ${docs.length} body chunks (${tagSet.size} unique tags)`,
);
